baseurl = "https://markuseliasson.se"
languageCode = "en-us"
title = "Markus Eliasson"
paginate = 10

[params]
    author = "Markus Eliasson"
    authorBio = "A thorough technical lead with a passion for producing valuable and clean code. Tends to occasionally blog about building software and can't seem to make up his mind on which programming language to use next."
    authorEmail = "markus.eliasson@gmail.com"

[[menu.footer]]
    name = "GitHub"
    url = "https://github.com/eliasson"
    pre = "<use xlink:href=\"#icon-github\"></use>"
    weight = 10

[[menu.footer]]
    name = "Twitter"
    url = "https://twitter.com/markuseliasson"
    pre = "<use xlink:href=\"#icon-twitter\"></use>"
    weight = 20

[[menu.footer]]
    name = "LinkedIn"
    url = "http://www.linkedin.com/in/markuseliasson"
    pre = "<use xlink:href=\"#icon-linkedin\"></use>"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true