name = "eliasson"
license = "MIT"
licenselink = "https://github.com/eliasson/markuseliasson/README.md"
description = "A minimal theme with a personal touch"
homepage = "http://www.markuseliasson.se"
tags = ["", ""]
features = ["", ""]
min_version = 0.121

[author]
  name = "Markus Eliasson"
  homepage = "http://www.markuseliasson.se"
